# SPDX-License-Identifier: GPL-2.0-only
################################################################################
#
# Marvell (aQuantia) Ethernet Controller AQtion Linux Driver
# Copyright (C) 2020 Marvell International Ltd.
#
################################################################################

obj-y := atl_fake_hw.o \
	atl_fake_hw_regs.o \
	atl_fake_pci_func.o \
	atl_test_overflow.o \
